### ISSUE TITLE
fork?

### ISSUE THREAD

**Issue by paulirish** [uupaa/dynamic-import-polyfill#5]
@uupaa there are a few folks interested in this repo, but it looks like you don't have the time to maintain it. (which is totally fine)

are you okay if someone forks your repo and maintains it separately? It'll likely also be published to npm.

thank you!

**Comment by uupaa** [comment]
@paulirish Yes, that is no problem.

Since it is a good opportunity, I updated and published it on npm. #6

**Comment by philipwalton** [comment]
Hey @uupaa 👋thanks for confirming and publishing this to npm. I'm working on an article to promote the usage of dynamic import in people's projects (and hoping to recommend this polyfill), but I wanted to make a few changes to before doing so.

I've filed these issue/feature requests, let me know if you're interested in accepting a PR with all of these changes: https://github.com/uupaa/dynamic-import-polyfill/issues/7, https://github.com/uupaa/dynamic-import-polyfill/issues/8, https://github.com/uupaa/dynamic-import-polyfill/issues/9, https://github.com/uupaa/dynamic-import-polyfill/issues/10.

**Comment by philipwalton** [comment]
Hey @uupaa, polite ping. Any thoughts on whether these are features you'd be interested in adding? I'm happy to submit a PR. If not (or you're too busy) let me know and I can maintain a separate package with these features.

**Comment by rugk** [comment]
Is this still maintained? 🤔
